
finally


finally 는 try 문에서 오류가 발생하든 안 하든 무조건 실행하도록 하는 것.


class ero(Exception):
    pass

try:
        print("한 자리 수 나눗셈 계산기")
        num1 = int(input("숫자 입력"))
        num2 = int(input("숫자 입력"))
        if (num1 >=10) or (num2 >= 10):
                raise ero
        print("{0} % {1} = {2} 입니다.".format(num1, num2, int(num1/num2)))
    
except ero:
    print("10미만의 숫자를 입력해 주세요.")

fianlly:
    print("계산기를 이용해 주셔서 감사합니다.")


이렇게 finally를 이용하면 "계산기를 이용해 주셔서 감사합니다."가 무조건 출력됨.